# Generated by Django 5.2.4 on 2025-07-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_origem', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50)),
                ('fonte_correcao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Correção',
                'verbose_name_plural': 'Correções',
            },
        ),
        migrations.CreateModel(
            name='tipoTese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeseCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_origem', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50)),
                ('jurisprudencia', models.CharField(max_length=200)),
                ('corrige', models.BooleanField(default=False)),
                ('correcao', models.IntegerField(blank=True, null=True)),
                ('id_correcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correcao.correcao')),
                ('id_tipo_tese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correcao.tipotese')),
            ],
        ),
    ]
