# Generated by Django 5.2.4 on 2025-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_origem', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50)),
                ('fonte_correcao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Correção',
                'verbose_name_plural': 'Correções',
            },
        ),
    ]
