# Generated by Django 5.2.4 on 2025-08-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('fonte_correcao', models.CharField(max_length=200)),
                ('cod_origem', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Correção',
                'verbose_name_plural': 'Correções',
            },
        ),
        migrations.CreateModel(
            name='tipoTese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Categoria')),
                ('periodicidade', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral')], default='mensal', max_length=20, verbose_name='Periodicidade')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.CreateModel(
            name='TeseCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('jurisprudencia', models.CharField(max_length=200)),
                ('corrige', models.BooleanField(blank=True, default=False, null=True)),
                ('cod_origem', models.CharField(blank=True, max_length=20, null=True)),
                ('id_correcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='correcao.correcao', verbose_name='Índice de Correção')),
                ('id_tipo_tese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correcao.tipotese', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Forma de Habilitação',
                'verbose_name_plural': 'Formas de Habilitações',
            },
        ),
    ]
