# Generated by Django 5.2.4 on 2025-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcao',
            name='cod_origem',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
