# Generated by Django 5.2.4 on 2025-07-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0002_alter_correcao_cod_origem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesecredito',
            name='correcao',
        ),
        migrations.AlterField(
            model_name='tesecredito',
            name='cod_origem',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tesecredito',
            name='corrige',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tesecredito',
            name='id_correcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='correcao.correcao', verbose_name='Índice de Correção'),
        ),
        migrations.AlterField(
            model_name='tesecredito',
            name='id_tipo_tese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correcao.tipotese', verbose_name='Tipo de Tese'),
        ),
    ]
