# Generated by Django 5.2.4 on 2025-07-31 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0003_remove_tesecredito_correcao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tesecredito',
            options={'verbose_name': 'Forma de Habilitação'},
        ),
        migrations.AlterField(
            model_name='tesecredito',
            name='id_tipo_tese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='correcao.tipotese', verbose_name='Tipo de documento'),
        ),
    ]
