# Generated by Django 5.2.4 on 2025-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0004_alter_tesecredito_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tesecredito',
            options={'verbose_name': 'Forma de Habilitação', 'verbose_name_plural': 'Formas de Habilitações'},
        ),
        migrations.AlterModelOptions(
            name='tipotese',
            options={'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documentos'},
        ),
        migrations.AddField(
            model_name='tipotese',
            name='periodicidade',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral')], default='mensal', max_length=20, verbose_name='Periodicidade'),
        ),
    ]
