# Generated by Django 5.2.4 on 2025-09-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0004_historicaltipotese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltesecredito',
            name='corrige',
        ),
        migrations.RemoveField(
            model_name='historicaltesecredito',
            name='id_correcao',
        ),
        migrations.RemoveField(
            model_name='tesecredito',
            name='corrige',
        ),
        migrations.RemoveField(
            model_name='tesecredito',
            name='id_correcao',
        ),
    ]
