# Generated by Django 5.2.4 on 2025-09-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0005_remove_correcao_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correcao',
        ),
        migrations.DeleteModel(
            name='HistoricalCorrecao',
        ),
    ]
