# Generated by Django 5.2.4 on 2025-09-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0006_remove_correcao_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltesecredito',
            name='id_tipo_tese',
        ),
        migrations.RemoveField(
            model_name='tesecredito',
            name='id_tipo_tese',
        ),
        migrations.DeleteModel(
            name='HistoricaltipoTese',
        ),
        migrations.DeleteModel(
            name='tipoTese',
        ),
    ]
