# Generated by Django 5.2.4 on 2025-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('empresas', '0003_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='relacionamento',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='empresas',
            field=models.ManyToManyField(blank=True, help_text='Empresas que o usuário pode visualizar e gerenciar.', to='empresas.empresa', verbose_name='Empresas Acessíveis'),
        ),
    ]
