# Generated by Django 5.2.4 on 2025-09-12 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_relacionamento_and_more'),
        ('empresas', '0003_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='empresa_ativa',
            field=models.ForeignKey(blank=True, help_text='A empresa atualmente selecionada pelo usuário para visualização.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='empresas.empresa', verbose_name='Empresa Ativa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='empresas',
            field=models.ManyToManyField(blank=True, help_text='Empresas que o usuário pode visualizar e gerenciar.', related_name='user_profiles', to='empresas.empresa', verbose_name='Empresas Acessíveis'),
        ),
    ]
