# Generated by Django 5.2.4 on 2025-09-12 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_empresa_ativa_alter_userprofile_empresas'),
        ('empresas', '0003_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='empresa_ativa',
            field=models.ForeignKey(blank=True, help_text='Empresa atualmente selecionada pelo usuário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_como_ativa', to='empresas.empresa', verbose_name='Empresa Ativa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='empresas',
            field=models.ManyToManyField(blank=True, help_text='Empresas que o usuário pode visualizar e gerenciar.', to='empresas.empresa', verbose_name='Empresas Acessíveis'),
        ),
    ]
