# Generated by Django 5.2.4 on 2025-09-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_empresa_ativa_and_more'),
        ('empresas', '0004_socio_participacaosocietaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='empresa_ativa',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='empresas_parceiras',
            field=models.ManyToManyField(blank=True, help_text='Empresas (parceiros) que o usuário pode visualizar e gerenciar.', related_name='usuarios_parceiros', to='empresas.empresa', verbose_name='Empresas Parceiras Acessíveis'),
        ),
    ]
