# Generated by Django 5.2.4 on 2025-09-15 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_empresa_ativa_and_more'),
        ('empresas', '0004_socio_participacaosocietaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='empresas_parceiras',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='empresa_parceira',
            field=models.ForeignKey(blank=True, help_text='Se definido, o usuário atua como parceiro e não pode ter empresas clientes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_parceiros', to='empresas.empresa', verbose_name='Empresa Parceira'),
        ),
    ]
