# Generated by Django 5.2.4 on 2025-09-18 13:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_empresas_parceiras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UserProfile._foto_upload_path, verbose_name='Foto de Perfil'),
        ),
    ]
