# Generated by Django 5.2.4 on 2025-08-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_parceiros', '0001_initial'),
        ('correcao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data em que a adesão foi iniciada', verbose_name='Data de Início')),
                ('perdcomp', models.CharField(blank=True, max_length=30, null=True, verbose_name='PERDCOMP')),
                ('saldo', models.FloatField(verbose_name='Valor do crédito')),
                ('ano_trimestre', models.CharField(blank=True, max_length=7, null=True, verbose_name='Ano/Trimestre')),
                ('periodo_apuracao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração')),
                ('periodo_apuracao_um', models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração 1')),
                ('codigo_receita', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Receita')),
                ('codigo_receita_denominacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Receita / Denominação')),
                ('credito_original_utilizado', models.FloatField(blank=True, null=True, verbose_name='Crédito Original Utilizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('saldo_atual', models.FloatField(blank=True, help_text='Saldo atual da adesão, atualizado automaticamente pelos lançamentos', null=True, verbose_name='Saldo Atual')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='clientes_parceiros.clientesparceiros')),
                ('tese_credito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='correcao.tesecredito', verbose_name='Tese de Crédito')),
            ],
            options={
                'verbose_name': 'Adesão',
                'verbose_name_plural': 'Adesões',
            },
        ),
    ]
