# Generated by Django 5.2.4 on 2025-08-13 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_parceiros', '0001_initial'),
        ('correcao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_credito', models.CharField(blank=True, choices=[('Pedido de compensação', 'Pedido de compensação'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação', 'Declaração de compensação'), ('Declaração de compensação pagamento indevido', 'Declaração de compensação pagamento indevido')], max_length=50, null=True, verbose_name='Método de Crédito')),
                ('data_inicio', models.DateField(help_text='Data em que a adesão foi iniciada', verbose_name='Data de Início')),
                ('perdcomp', models.CharField(blank=True, max_length=30, null=True, verbose_name='PERDCOMP')),
                ('saldo', models.FloatField(verbose_name='Valor do crédito')),
                ('ano_trimestre', models.DateField(blank=True, help_text='Armazenado como primeiro dia do mês. Exibição mm/aaaa.', null=True, verbose_name='Mês/Ano')),
                ('periodo_apuracao_credito', models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração Crédito')),
                ('periodo_apuracao_debito', models.CharField(blank=True, max_length=20, null=True, verbose_name='Periodo apuração débito')),
                ('tipo_credito', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Crédito')),
                ('codigo_receita', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Receita')),
                ('codigo_receita_denominacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Receita / Denominação')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('credito_original_utilizado', models.FloatField(blank=True, null=True, verbose_name='Crédito Original Utilizado')),
                ('valor_do_principal', models.FloatField(blank=True, null=True, verbose_name='Valor do Principal')),
                ('saldo_atual', models.FloatField(blank=True, help_text='Saldo atual da adesão, atualizado automaticamente pelos lançamentos', null=True, verbose_name='Saldo Atual')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='clientes_parceiros.clientesparceiros')),
                ('tese_credito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='correcao.tesecredito', verbose_name='Tese de Crédito')),
            ],
            options={
                'verbose_name': 'Adesão',
                'verbose_name_plural': 'Adesões',
            },
        ),
    ]
