# Generated by Django 5.2.4 on 2025-07-14 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_parceiros', '0001_initial'),
        ('correcao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data em que a adesão foi iniciada', verbose_name='Data de Início')),
                ('perdcomp', models.CharField(max_length=30, verbose_name='PERDCOMP')),
                ('saldo', models.FloatField(verbose_name='Saldo')),
                ('free_rate', models.FloatField(verbose_name='Free Rate')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='clientes_parceiros.clientesparceiros')),
                ('tese_credito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='correcao.tesecredito')),
            ],
        ),
    ]
