# Generated by Django 5.2.4 on 2025-08-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de compensação', 'Pedido de compensação'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação', 'Declaração de compensação')], max_length=50, null=True, verbose_name='Método de Crédito'),
        ),
    ]
