# Generated by Django 5.2.4 on 2025-07-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='saldo_atual',
            field=models.FloatField(default=1212, verbose_name='Saldo Atual'),
            preserve_default=False,
        ),
    ]
