# Generated by Django 5.2.4 on 2025-07-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0001_initial'),
        ('correcao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adesao',
            name='correcao',
        ),
        migrations.AddField(
            model_name='adesao',
            name='tese_credito_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='correcao.tesecredito'),
            preserve_default=False,
        ),
    ]
