# Generated by Django 5.2.4 on 2025-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adesao',
            name='ano_trimestre',
        ),
        migrations.AddField(
            model_name='adesao',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='trimestre',
            field=models.CharField(blank=True, choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre'), ('4', '4º Trimestre')], max_length=1, null=True, verbose_name='Trimestre'),
        ),
    ]
