# Generated by Django 5.2.4 on 2025-07-18 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adesao', '0001_initial'),
        ('clientes_parceiros', '0001_initial'),
        ('correcao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='clientes_parceiros.clientesparceiros'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='tese_credito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adesoes', to='correcao.tesecredito', verbose_name='Tese de Crédito'),
        ),
    ]
