# Generated by Django 5.2.4 on 2025-08-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0002_remove_adesao_ano_trimestre_adesao_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adesao',
            name='perdcomp',
            field=models.CharField(default=1, max_length=30, verbose_name='PERDCOMP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adesao',
            name='saldo',
            field=models.FloatField(verbose_name='Valor do crédito '),
        ),
    ]
