# Generated by Django 5.2.4 on 2025-08-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0002_adesao_metodo_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adesao',
            name='periodo_apuracao',
        ),
        migrations.RemoveField(
            model_name='adesao',
            name='periodo_apuracao_um',
        ),
        migrations.AddField(
            model_name='adesao',
            name='periodo_apuracao_credito',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração Crédito'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='periodo_apuracao_debito',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Periodo apuração débito'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='valor_do_principal',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor do Principal'),
        ),
        migrations.AlterField(
            model_name='adesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de compensação', 'Pedido de compensação'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação', 'Declaração de compensação'), ('Declaração de compensação pagamento indevido', 'Declaração de compensação pagamento indevido')], max_length=50, null=True, verbose_name='Método de Crédito'),
        ),
    ]
