# Generated by Django 5.2.4 on 2025-07-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0002_adesao_saldo_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adesao',
            name='saldo_atual',
            field=models.FloatField(help_text='Saldo atual da adesão, atualizado automaticamente pelos lançamentos', verbose_name='Saldo Atual'),
        ),
    ]
