# Generated by Django 5.2.4 on 2025-08-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0003_remove_adesao_periodo_apuracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='tipo_credito',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Crédito'),
        ),
    ]
