# Generated by Django 5.2.4 on 2025-07-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0003_alter_adesao_saldo_atual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adesao',
            options={'verbose_name': 'Adesão', 'verbose_name_plural': 'Adesões'},
        ),
    ]
