# Generated by Django 5.2.4 on 2025-09-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0004_historicaladesao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de ressarcimento', 'Pedido de ressarcimento'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação pagamento indevido', 'Declaração de compensação pagamento indevido')], max_length=50, null=True, verbose_name='Método de Crédito'),
        ),
        migrations.AlterField(
            model_name='historicaladesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de ressarcimento', 'Pedido de ressarcimento'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação pagamento indevido', 'Declaração de compensação pagamento indevido')], max_length=50, null=True, verbose_name='Método de Crédito'),
        ),
    ]
