# Generated by Django 5.2.4 on 2025-08-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0004_adesao_tipo_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adesao',
            name='tipo_credito',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Crédito'),
        ),
    ]
