# Generated by Django 5.2.4 on 2025-09-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0005_alter_adesao_metodo_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='selic_acumulada',
            field=models.FloatField(blank=True, help_text='Taxa SELIC acumulada para cálculo de correção - apenas informativo', null=True, verbose_name='SELIC Acumulada (%)'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='valor_correcao',
            field=models.FloatField(blank=True, help_text='Valor da correção monetária aplicada - apenas informativo', null=True, verbose_name='Valor da Correção'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='valor_total_corrigido',
            field=models.FloatField(blank=True, help_text='Valor principal + correção monetária - apenas informativo', null=True, verbose_name='Valor Total Corrigido'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='selic_acumulada',
            field=models.FloatField(blank=True, help_text='Taxa SELIC acumulada para cálculo de correção - apenas informativo', null=True, verbose_name='SELIC Acumulada (%)'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='valor_correcao',
            field=models.FloatField(blank=True, help_text='Valor da correção monetária aplicada - apenas informativo', null=True, verbose_name='Valor da Correção'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='valor_total_corrigido',
            field=models.FloatField(blank=True, help_text='Valor principal + correção monetária - apenas informativo', null=True, verbose_name='Valor Total Corrigido'),
        ),
    ]
