# Generated by Django 5.2.4 on 2025-09-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0006_add_restituicao_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='data_arrecadacao',
            field=models.DateField(blank=True, help_text='Data em que ocorreu a arrecadação relacionada', null=True, verbose_name='Data de Arrecadação'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='data_arrecadacao',
            field=models.DateField(blank=True, help_text='Data em que ocorreu a arrecadação relacionada', null=True, verbose_name='Data de Arrecadação'),
        ),
    ]
