# Generated by Django 5.2.4 on 2025-10-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0007_adesao_data_arrecadacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adesao',
            name='tese_credito_id',
        ),
        migrations.RemoveField(
            model_name='historicaladesao',
            name='tese_credito_id',
        ),
    ]
