# Generated by Django 5.2.4 on 2025-10-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0008_remove_adesao_tese_credito_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='data_origem',
            field=models.DateField(blank=True, help_text='Data da origem do crédito (escritural)', null=True, verbose_name='Data de Origem'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='origem',
            field=models.CharField(blank=True, help_text='Origem do crédito (escritural)', max_length=255, null=True, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='data_origem',
            field=models.DateField(blank=True, help_text='Data da origem do crédito (escritural)', null=True, verbose_name='Data de Origem'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='origem',
            field=models.CharField(blank=True, help_text='Origem do crédito (escritural)', max_length=255, null=True, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='adesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de ressarcimento', 'Pedido de ressarcimento'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação pagamento indevido', 'Declaração de compensação pagamento indevido'), ('Escritural', 'Escritural')], max_length=50, null=True, verbose_name='Método de Crédito'),
        ),
        migrations.AlterField(
            model_name='historicaladesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de ressarcimento', 'Pedido de ressarcimento'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação pagamento indevido', 'Declaração de compensação pagamento indevido'), ('Escritural', 'Escritural')], max_length=50, null=True, verbose_name='Método de Crédito'),
        ),
    ]
