# Generated by Django 5.2.4 on 2025-10-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0009_adesao_data_origem_adesao_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de ressarcimento', 'Pedido de ressarcimento'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação pagamento indevido', 'Declaração de compensação pagamento indevido'), ('Compensação vinculada a um pedido de ressarcimento', 'Compensação vinculada a um pedido de ressarcimento'), ('Compensação vinculada a um pedido de restituição', 'Compensação vinculada a um pedido de restituição'), ('Escritural', 'Escritural')], max_length=50, null=True, verbose_name='Tipo de Crédito'),
        ),
        migrations.AlterField(
            model_name='historicaladesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de ressarcimento', 'Pedido de ressarcimento'), ('Pedido de restituição', 'Pedido de restituição'), ('Declaração de compensação pagamento indevido', 'Declaração de compensação pagamento indevido'), ('Compensação vinculada a um pedido de ressarcimento', 'Compensação vinculada a um pedido de ressarcimento'), ('Compensação vinculada a um pedido de restituição', 'Compensação vinculada a um pedido de restituição'), ('Escritural', 'Escritural')], max_length=50, null=True, verbose_name='Tipo de Crédito'),
        ),
    ]
