# Generated by Django 5.2.4 on 2025-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0011_alter_adesao_metodo_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='chave_seguranca_serpro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave de Segurança SERPRO'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='numero_controle',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Número de Controle'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado')], default='solicitado', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='chave_seguranca_serpro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave de Segurança SERPRO'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='numero_controle',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Número de Controle'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado')], default='solicitado', max_length=20, verbose_name='Status'),
        ),
    ]
