# Generated by Django 5.2.4 on 2025-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0012_adesao_chave_seguranca_serpro_adesao_numero_controle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao',
            name='data_credito_em_conta',
            field=models.DateField(blank=True, help_text='Data comunicada na notificação de crédito em conta', null=True, verbose_name='Data do Crédito em Conta'),
        ),
        migrations.AddField(
            model_name='adesao',
            name='valor_credito_em_conta',
            field=models.FloatField(blank=True, help_text='Valor creditado informado na notificação', null=True, verbose_name='Valor do Crédito em Conta'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='data_credito_em_conta',
            field=models.DateField(blank=True, help_text='Data comunicada na notificação de crédito em conta', null=True, verbose_name='Data do Crédito em Conta'),
        ),
        migrations.AddField(
            model_name='historicaladesao',
            name='valor_credito_em_conta',
            field=models.FloatField(blank=True, help_text='Valor creditado informado na notificação', null=True, verbose_name='Valor do Crédito em Conta'),
        ),
    ]