# Generated by Django 5.2.4 on 2025-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0013_adesao_data_credito_em_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de ressarcimento', 'Pedido de ressarcimento'), ('Pedido de restituição', 'Pedido de restituição'), ('Compensação vinculada a um pedido de ressarcimento', 'Compensação vinculada a um pedido de ressarcimento'), ('Compensação vinculada a um pedido de restituição', 'Compensação vinculada a um pedido de restituição'), ('Escritural', 'Escritural'), ('Crédito em conta', 'Crédito em conta'), ('Declaração de Compensação', 'Declaração de Compensação')], max_length=50, null=True, verbose_name='Tipo de Crédito'),
        ),
        migrations.AlterField(
            model_name='historicaladesao',
            name='metodo_credito',
            field=models.CharField(blank=True, choices=[('Pedido de ressarcimento', 'Pedido de ressarcimento'), ('Pedido de restituição', 'Pedido de restituição'), ('Compensação vinculada a um pedido de ressarcimento', 'Compensação vinculada a um pedido de ressarcimento'), ('Compensação vinculada a um pedido de restituição', 'Compensação vinculada a um pedido de restituição'), ('Escritural', 'Escritural'), ('Crédito em conta', 'Crédito em conta'), ('Declaração de Compensação', 'Declaração de Compensação')], max_length=50, null=True, verbose_name='Tipo de Crédito'),
        ),
    ]
