# Generated by Django 5.2.4 on 2025-10-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0015_adesao_perdcomp_retificador_and_alter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaladesao',
            name='perdcomp_retificador',
            field=models.CharField(blank=True, help_text='Número do PER/DCOMP retificador vinculado a esta adesão.', max_length=30, null=True, verbose_name='PERDCOMP retificador'),
        ),
        migrations.AlterField(
            model_name='historicaladesao',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado'), ('retificado', 'Retificado')], default='solicitado', max_length=20, verbose_name='Status'),
        ),
    ]
