# Generated by Django 5.2.4 on 2025-08-13 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adesao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateTimeField(help_text='Data em que o lançamento foi realizado', verbose_name='Data do Lançamento')),
                ('valor', models.FloatField(help_text='Valor do lançamento realizado', verbose_name='Valor do Lançamento')),
                ('sinal', models.CharField(choices=[('+', 'Crédito'), ('-', 'Débito')], default='+', help_text='Indica se o lançamento é um crédito ou débito', max_length=1, verbose_name='Sinal do Lançamento')),
                ('tipo', models.CharField(blank=True, choices=[('Gerado', 'GERADO'), ('Correção', 'CORREÇÃO'), ('Originado no Ecac', 'ORIGINADO NO ECAC')], max_length=20, null=True, verbose_name='Tipo de Lançamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('saldo_restante', models.FloatField(blank=True, help_text='Saldo da adesão após este lançamento', null=True, verbose_name='Saldo Restante')),
                ('id_adesao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='adesao.adesao', verbose_name='Adesão')),
            ],
        ),
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/lancamentos/', verbose_name='Arquivo')),
                ('nome_anexo', models.CharField(max_length=100, verbose_name='Nome do anexo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do conteúdo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('id_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='lancamentos.lancamentos', verbose_name='Lançamento')),
            ],
        ),
    ]
