# Generated by Django 5.2.4 on 2025-07-14 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='lancamento_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_estorno', to='lancamentos.lancamentos', verbose_name='Lançamento Original'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=20, verbose_name='Status do Lançamento'),
        ),
    ]
