# Generated by Django 5.2.4 on 2025-08-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='debito',
            field=models.FloatField(blank=True, null=True, verbose_name='Débito (Restituição)'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='debito_r',
            field=models.FloatField(blank=True, null=True, verbose_name='Débito (Ressarcimento)'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='metodo',
            field=models.CharField(blank=True, help_text='Pedido de ressarcimento, Pedido de restituição, etc.', max_length=60, null=True, verbose_name='Método do Lançamento'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='periodo_apuracao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='periodo_apuracao_r',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração (Ressarcimento)'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total (Ressarcimento / Compensação)'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='total_credito_original_utilizado',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Crédito Original Utilizado (Restituição)'),
        ),
    ]
