# Generated by Django 5.2.4 on 2025-08-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamentos',
            old_name='observacao',
            new_name='descricao',
        ),
    ]
