# Generated by Django 5.2.4 on 2025-07-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_add_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='saldo_restante',
            field=models.FloatField(blank=True, help_text='Saldo da adesão após este lançamento', null=True, verbose_name='Saldo Restante'),
        ),
    ]
