# Generated by Django 5.2.4 on 2025-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_lancamentos_debito_lancamentos_debito_r_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='valor',
            field=models.FloatField(blank=True, help_text='Valor do lançamento realizado', null=True, verbose_name='Valor do Lançamento'),
        ),
    ]
