# Generated by Django 5.2.4 on 2025-08-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0003_alter_lancamentos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexos',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do conteúdo'),
        ),
        migrations.AlterField(
            model_name='anexos',
            name='nome_anexo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do anexo'),
        ),
    ]
