# Generated by Django 5.2.4 on 2025-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0003_lancamentos_saldo_restante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='data_lancamento',
            field=models.DateTimeField(help_text='Data em que o lançamento foi realizado', verbose_name='Data do Lançamento'),
        ),
    ]
