# Generated by Django 5.2.4 on 2025-08-21 18:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0004_historicaladesao'),
        ('lancamentos', '0004_alter_anexos_descricao_alter_anexos_nome_anexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAnexos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('arquivo', models.TextField(max_length=100, verbose_name='Arquivo')),
                ('nome_anexo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do anexo')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do conteúdo')),
                ('data_upload', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Upload')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_lancamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lancamentos.lancamentos', verbose_name='Lançamento')),
            ],
            options={
                'verbose_name': 'historical anexos',
                'verbose_name_plural': 'historical anexoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLancamentos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_lancamento', models.DateTimeField(help_text='Data em que o lançamento foi realizado', verbose_name='Data do Lançamento')),
                ('valor', models.FloatField(blank=True, help_text='Valor do lançamento realizado', null=True, verbose_name='Valor do Lançamento')),
                ('sinal', models.CharField(choices=[('+', 'Crédito'), ('-', 'Débito')], default='+', help_text='Indica se o lançamento é um crédito ou débito', max_length=1, verbose_name='Sinal do Lançamento')),
                ('tipo', models.CharField(blank=True, choices=[('Gerado', 'GERADO'), ('Correção', 'CORREÇÃO'), ('Originado no Ecac', 'ORIGINADO NO ECAC')], max_length=20, null=True, verbose_name='Tipo de Lançamento')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('saldo_restante', models.FloatField(blank=True, help_text='Saldo da adesão após este lançamento', null=True, verbose_name='Saldo Restante')),
                ('metodo', models.CharField(blank=True, help_text='Pedido de ressarcimento, Pedido de restituição, etc.', max_length=60, null=True, verbose_name='Método do Lançamento')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total (Ressarcimento / Compensação)')),
                ('total_credito_original_utilizado', models.FloatField(blank=True, null=True, verbose_name='Total Crédito Original Utilizado (Restituição)')),
                ('periodo_apuracao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração')),
                ('periodo_apuracao_r', models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração (Ressarcimento)')),
                ('debito', models.FloatField(blank=True, null=True, verbose_name='Débito (Restituição)')),
                ('debito_r', models.FloatField(blank=True, null=True, verbose_name='Débito (Ressarcimento)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_adesao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='adesao.adesao', verbose_name='Adesão')),
            ],
            options={
                'verbose_name': 'historical lancamentos',
                'verbose_name_plural': 'historical lancamentoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
