# Generated by Django 5.2.4 on 2025-07-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0004_alter_lancamentos_data_lancamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentos',
            name='data_confirmacao',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='lancamento_original',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='status',
        ),
    ]
