# Generated by Django 5.2.4 on 2025-09-07 23:16

import django.core.validators
import lancamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0005_historicalanexos_historicallancamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexos',
            name='arquivo',
            field=models.FileField(upload_to=lancamentos.models.Anexos._anexo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'csv', 'xlsx', 'xls']), lancamentos.models.Anexos.validar_tamanho], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='historicalanexos',
            name='arquivo',
            field=models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'csv', 'xlsx', 'xls']), lancamentos.models.Anexos.validar_tamanho], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='historicallancamentos',
            name='sinal',
            field=models.CharField(choices=[('+', 'Crédito'), ('-', 'Débito')], default='-', help_text='Indica se o lançamento é um crédito ou débito', max_length=1, verbose_name='Sinal do Lançamento'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='sinal',
            field=models.CharField(choices=[('+', 'Crédito'), ('-', 'Débito')], default='-', help_text='Indica se o lançamento é um crédito ou débito', max_length=1, verbose_name='Sinal do Lançamento'),
        ),
    ]
