# Generated by Django 5.2.4 on 2025-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0006_alter_anexos_arquivo_alter_historicalanexos_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallancamentos',
            name='data_lancamento',
            field=models.DateTimeField(help_text='Data em que o pedido foi realizado', verbose_name='Data do pedido'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='data_lancamento',
            field=models.DateTimeField(help_text='Data em que o pedido foi realizado', verbose_name='Data do pedido'),
        ),
    ]
