# Generated by Django 5.2.4 on 2025-09-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0008_historicallancamentos_aprovado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='observacao_aprovacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Aprovação'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='observacao_aprovacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Aprovação'),
        ),
    ]
