# Generated by Django 5.2.4 on 2025-10-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0009_historicallancamentos_observacao_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='codigo_receita',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Receita (Débito)'),
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='codigo_receita_denominacao',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Código Receita / Denominação (Débito)'),
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='periodo_apuracao_debito',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração (Débito)'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='codigo_receita',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Receita (Débito)'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='codigo_receita_denominacao',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Código Receita / Denominação (Débito)'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='periodo_apuracao_debito',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Apuração (Débito)'),
        ),
    ]
