# Generated by Django 5.2.4 on 2025-10-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0010_historicallancamentos_codigo_receita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='codigo_guia',
            field=models.CharField(blank=True, help_text='Identificador da guia vinculada ao lançamento.', max_length=60, null=True, verbose_name='Código da Guia'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='codigo_guia',
            field=models.CharField(blank=True, help_text='Identificador da guia vinculada ao lançamento.', max_length=60, null=True, verbose_name='Código da Guia'),
        ),
    ]
