# Generated by Django 5.2.4 on 2025-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0011_lancamentos_codigo_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='data_credito',
            field=models.DateField(blank=True, help_text='Data em que o crédito foi efetivado em conta', null=True, verbose_name='Data do Crédito'),
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='valor_credito_em_conta',
            field=models.FloatField(blank=True, help_text='Valor creditado conforme notificação', null=True, verbose_name='Valor do Crédito em Conta'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='data_credito',
            field=models.DateField(blank=True, help_text='Data em que o crédito foi efetivado em conta', null=True, verbose_name='Data do Crédito'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='valor_credito_em_conta',
            field=models.FloatField(blank=True, help_text='Valor creditado conforme notificação', null=True, verbose_name='Valor do Crédito em Conta'),
        ),
    ]
