# Generated by Django 5.2.4 on 2025-10-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0012_lancamentos_data_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='item',
            field=models.CharField(blank=True, help_text='Código do item do débito dentro da declaração de compensação.', max_length=10, null=True, verbose_name='Item da Declaração'),
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='perdcomp',
            field=models.CharField(blank=True, help_text='Identificador da declaração de compensação que originou este lançamento.', max_length=100, null=True, verbose_name='PER/DCOMP da Declaração'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='item',
            field=models.CharField(blank=True, help_text='Código do item do débito dentro da declaração de compensação.', max_length=10, null=True, verbose_name='Item da Declaração'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='perdcomp',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador da declaração de compensação que originou este lançamento.', max_length=100, null=True, verbose_name='PER/DCOMP da Declaração'),
        ),
        migrations.AlterUniqueTogether(
            name='lancamentos',
            unique_together={('perdcomp', 'item')},
        ),
    ]
