# Generated by Django 5.2.4 on 2025-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0014_alter_adesao_metodo_credito_and_more'),
        ('lancamentos', '0013_lancamentos_perdcomp_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallancamentos',
            name='perdcomp',
        ),
        migrations.AlterUniqueTogether(
            name='lancamentos',
            unique_together={('id_adesao', 'item')},
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='perdcomp_declaracao',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador da declaração de compensação de onde este item foi importado.', max_length=100, null=True, verbose_name='PER/DCOMP da Declaração'),
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='perdcomp_inicial',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador da PER/DCOMP utilizada na adesão relacionada.', max_length=100, null=True, verbose_name='PER/DCOMP Inicial'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='perdcomp_declaracao',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador da declaração de compensação de onde este item foi importado.', max_length=100, null=True, verbose_name='PER/DCOMP da Declaração'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='perdcomp_inicial',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador da PER/DCOMP utilizada na adesão relacionada.', max_length=100, null=True, verbose_name='PER/DCOMP Inicial'),
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='perdcomp',
        ),
    ]
