# Generated by Django 5.2.4 on 2025-10-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0014_alter_adesao_metodo_credito_and_more'),
        ('lancamentos', '0014_remove_historicallancamentos_perdcomp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lancamentos',
            unique_together={('id_adesao', 'perdcomp_declaracao', 'item')},
        ),
    ]
