# Generated by Django 5.2.4 on 2025-10-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0015_alter_lancamentos_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallancamentos',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='historicallancamentos',
            name='debito_r',
        ),
        migrations.RemoveField(
            model_name='historicallancamentos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='debito_r',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='tipo',
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='descricao_debitos',
            field=models.TextField(blank=True, help_text='Detalhamento dos itens de débito da declaração de compensação', null=True, verbose_name='Descrição dos Débitos'),
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='total_debitos_documento',
            field=models.FloatField(blank=True, help_text='Valor total dos débitos conforme declaração de compensação', null=True, verbose_name='Total dos Débitos deste Documento'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='descricao_debitos',
            field=models.TextField(blank=True, help_text='Detalhamento dos itens de débito da declaração de compensação', null=True, verbose_name='Descrição dos Débitos'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='total_debitos_documento',
            field=models.FloatField(blank=True, help_text='Valor total dos débitos conforme declaração de compensação', null=True, verbose_name='Total dos Débitos deste Documento'),
        ),
    ]
