# Generated by Django 5.2.4 on 2025-10-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0016_remove_historicallancamentos_debito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='chave_seguranca_serpro',
            field=models.CharField(blank=True, help_text='Chave de autenticação SERPRO do recibo', max_length=100, null=True, verbose_name='Chave de Segurança SERPRO'),
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='numero_controle',
            field=models.CharField(blank=True, help_text='Número de controle do recibo de envio da declaração', max_length=50, null=True, verbose_name='Número de Controle'),
        ),
        migrations.AddField(
            model_name='historicallancamentos',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado')], default='solicitado', help_text='Status do lançamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='chave_seguranca_serpro',
            field=models.CharField(blank=True, help_text='Chave de autenticação SERPRO do recibo', max_length=100, null=True, verbose_name='Chave de Segurança SERPRO'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='numero_controle',
            field=models.CharField(blank=True, help_text='Número de controle do recibo de envio da declaração', max_length=50, null=True, verbose_name='Número de Controle'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado')], default='solicitado', help_text='Status do lançamento', max_length=20, verbose_name='Status'),
        ),
    ]
