# Generated by Django 5.2.4 on 2025-11-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0017_historicallancamentos_chave_seguranca_serpro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='perdcomp_retificador',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador da declaração retificadora vinculada a este lançamento.', max_length=100, null=True, verbose_name='PER/DCOMP Retificador'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='perdcomp_retificador',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador da declaração retificadora vinculada a este lançamento.', max_length=100, null=True, verbose_name='PER/DCOMP Retificador'),
        ),
        migrations.AlterField(
            model_name='historicallancamentos',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado'), ('retificado', 'Retificado')], default='solicitado', help_text='Status do lançamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado'), ('retificado', 'Retificado')], default='solicitado', help_text='Status do lançamento', max_length=20, verbose_name='Status'),
        ),
    ]
