# Generated by Django 5.2.4 on 2025-10-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0018_lancamentos_perdcomp_retificador_and_alter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallancamentos',
            name='perdcomp_inicial',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='perdcomp_inicial',
        ),
    ]
