# Generated by Django 5.2.4 on 2025-10-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0019_remove_perdcomp_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='is_retificadora',
            field=models.BooleanField(default=False, help_text='Indica se esta declaração é retificadora de outra declaração anterior.', verbose_name='É Retificadora'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='is_retificadora',
            field=models.BooleanField(default=False, help_text='Indica se esta declaração é retificadora de outra declaração anterior.', verbose_name='É Retificadora'),
        ),
    ]
