# Generated by Django 5.2.4 on 2025-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0020_add_is_retificadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentos',
            name='perdcomp_retificado',
            field=models.CharField(blank=True, db_index=True, help_text='Número do PER/DCOMP que está sendo retificado por esta declaração (quando is_retificadora=True).', max_length=100, null=True, verbose_name='PER/DCOMP Retificado'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='perdcomp_retificado',
            field=models.CharField(blank=True, db_index=True, help_text='Número do PER/DCOMP que está sendo retificado por esta declaração (quando is_retificadora=True).', max_length=100, null=True, verbose_name='PER/DCOMP Retificado'),
        ),
    ]
