# Generated by Django 5.2.4 on 2025-10-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0021_add_perdcomp_retificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallancamentos',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado'), ('retificado', 'Retificado'), ('estornado', 'Estornado após retificação')], default='solicitado', help_text='Status do lançamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('protocolado', 'Protocolado'), ('retificado', 'Retificado'), ('estornado', 'Estornado após retificação')], default='solicitado', help_text='Status do lançamento', max_length=20, verbose_name='Status'),
        ),
    ]
