# Generated by Django 5.2.4 on 2025-07-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRelacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacionamento', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientesParceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_referencia', models.CharField(max_length=200)),
                ('cargo_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio_parceria', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_company_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_parceiros_base', to='empresas.empresa')),
                ('id_company_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_parceiros_vinculada', to='empresas.empresa')),
                ('id_tipo_relacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_parceiros', to='clientes_parceiros.tiporelacionamento')),
            ],
        ),
    ]
