# Generated by Django 5.2.4 on 2025-07-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiporelacionamento',
            options={'verbose_name': 'Vínculo', 'verbose_name_plural': 'Vínculos'},
        ),
        migrations.AlterField(
            model_name='clientesparceiros',
            name='id_tipo_relacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_parceiros', to='clientes_parceiros.tiporelacionamento', verbose_name='Vínculo'),
        ),
        migrations.AlterField(
            model_name='tiporelacionamento',
            name='tipo_relacionamento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Vínculo'),
        ),
    ]
