# Generated by Django 5.2.4 on 2025-08-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_parceiros', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    # Ordem corrigida: 1) AddField novo 2) AlterUniqueTogether usando novo campo 3) RemoveField antigo 4) DeleteModel relacionado
    operations = [
        migrations.AddField(
            model_name='clientesparceiros',
            name='tipo_parceria',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('parceiro', 'Parceiro')], default='cliente', max_length=10, verbose_name='Tipo de Parceria'),
        ),
        migrations.AlterUniqueTogether(
            name='clientesparceiros',
            unique_together={('id_company_base', 'id_company_vinculada', 'tipo_parceria')},
        ),
        migrations.RemoveField(
            model_name='clientesparceiros',
            name='id_tipo_relacionamento',
        ),
        migrations.DeleteModel(
            name='TipoRelacionamento',
        ),
    ]
