# Generated by Django 5.2.4 on 2025-07-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_parceiros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiporelacionamento',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='tiporelacionamento',
            name='tipo_relacionamento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
