# Generated by Django 5.2.4 on 2025-08-21 16:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_parceiros', '0002_alter_clientesparceiros_unique_together_and_more'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClientesParceiros',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_parceria', models.CharField(choices=[('cliente', 'Cliente'), ('parceiro', 'Parceiro')], default='cliente', max_length=10, verbose_name='Tipo de Parceria')),
                ('nome_referencia', models.CharField(max_length=200)),
                ('cargo_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio_parceria', models.DateField(blank=True, editable=False, verbose_name='Data de Início da Parceria')),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_company_base', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas.empresa')),
                ('id_company_vinculada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'historical Vínculo Empresarial',
                'verbose_name_plural': 'historical Vínculos Empresariais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
