# Generated by Django 5.2.4 on 2025-08-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(choices=[('Comercial', 'Comercial'), ('Celular', 'Celular'), ('Pessoal', 'Pessoal')], default='Comercial', max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('empresa_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_base_contato', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
