# Generated by Django 5.2.4 on 2025-07-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='tipo_contato',
            field=models.CharField(choices=[('Comercial', 'Comercial'), ('Celular', 'Celular'), ('Pessoal', 'Pessoal')], default='Comercial', max_length=20),
        ),
        migrations.DeleteModel(
            name='TipoContato',
        ),
    ]
