# Generated by Django 5.2.4 on 2025-07-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='empresa_vinculada',
        ),
    ]
