# Generated by Django 5.2.4 on 2025-07-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, verbose_name='Nome Fantasia')),
                ('codigo_origem', models.CharField(blank=True, max_length=20, verbose_name='Código de Origem')),
                ('logomarca', models.CharField(blank=True, max_length=100, verbose_name='Logomarca')),
            ],
        ),
    ]
