# Generated by Django 5.2.4 on 2025-07-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logomarca',
            field=models.ImageField(blank=True, null=True, upload_to='logomarcas/', verbose_name='Logomarca'),
        ),
    ]
