# Generated by Django 5.2.4 on 2025-09-07 23:16

import django.core.validators
import empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logomarca',
            field=models.ImageField(blank=True, null=True, upload_to=empresas.models.Empresa._logo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), empresas.models.Empresa.validar_logo_tamanho], verbose_name='Logomarca'),
        ),
    ]
