# Generated by Django 5.2.4 on 2025-07-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_data_cadastro_alter_empresa_logomarca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='data_cadastro',
        ),
    ]
