# Generated by Django 5.2.4 on 2025-09-12 18:37

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_logomarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True, validators=[utils.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
    ]
